const express=require('express');const path=require('path');const bcrypt=require('bcryptjs');const dotenv=require('dotenv');const db=require('./db');const {signToken,requireAuth}=require('./auth');
dotenv.config();
if(!process.env.JWT_SECRET){console.error('JWT_SECRET is missing. Copy .env.example to .env and set it.');process.exit(1)}
const app=express();app.use(express.json());app.use(express.urlencoded({extended:true}));app.use(express.static(path.join(__dirname,'..','public')));

app.get('/api/health',(req,res)=>res.json({status:'ok',message:'DTEN Task Manager API is running.'}));

app.post('/api/auth/signup',async(req,res)=>{try{const {name,email,password}=req.body;if(!name||!email||!password)return res.status(400).json({message:'Name, email and password are required.'});if(password.length<6)return res.status(400).json({message:'Password must be at least 6 characters.'});const cleanEmail=email.trim().toLowerCase();const [existing]=await db.execute('SELECT id FROM users WHERE email=?',[cleanEmail]);if(existing.length)return res.status(409).json({message:'An account with that email already exists.'});const hash=await bcrypt.hash(password,10);const [result]=await db.execute('INSERT INTO users(name,email,password_hash) VALUES(?,?,?)',[name.trim(),cleanEmail,hash]);const user={id:result.insertId,name:name.trim(),email:cleanEmail};res.status(201).json({message:'Account created successfully.',token:signToken(user),user})}catch(err){console.error(err);res.status(500).json({message:'Unable to create account.'})}});

app.post('/api/auth/login',async(req,res)=>{try{const {email,password}=req.body;if(!email||!password)return res.status(400).json({message:'Email and password are required.'});const [rows]=await db.execute('SELECT id,name,email,password_hash FROM users WHERE email=?',[email.trim().toLowerCase()]);if(!rows.length)return res.status(401).json({message:'Invalid email or password.'});const user=rows[0];const match=await bcrypt.compare(password,user.password_hash);if(!match)return res.status(401).json({message:'Invalid email or password.'});const publicUser={id:user.id,name:user.name,email:user.email};res.json({message:'Login successful.',token:signToken(publicUser),user:publicUser})}catch(err){console.error(err);res.status(500).json({message:'Unable to log in.'})}});

app.get('/api/tasks',requireAuth,async(req,res)=>{try{const search=(req.query.search||'').trim();const status=req.query.status||'';const priority=req.query.priority||'';let sql='SELECT id,title,description,status,priority,due_date,created_at,updated_at FROM tasks WHERE user_id=?';const params=[req.user.id];if(search){sql+=' AND (title LIKE ? OR description LIKE ?)';params.push(`%${search}%`,`%${search}%`)}if(['pending','in_progress','completed'].includes(status)){sql+=' AND status=?';params.push(status)}if(['low','medium','high'].includes(priority)){sql+=' AND priority=?';params.push(priority)}sql+=' ORDER BY due_date IS NULL, due_date ASC, created_at DESC';const [rows]=await db.execute(sql,params);res.json(rows)}catch(err){console.error(err);res.status(500).json({message:'Unable to load tasks.'})}});

app.post('/api/tasks',requireAuth,async(req,res)=>{try{const {title,description='',status='pending',priority='medium',due_date=null}=req.body;if(!title?.trim())return res.status(400).json({message:'Task title is required.'});if(!['pending','in_progress','completed'].includes(status)||!['low','medium','high'].includes(priority))return res.status(400).json({message:'Invalid status or priority.'});const [result]=await db.execute('INSERT INTO tasks(user_id,title,description,status,priority,due_date) VALUES(?,?,?,?,?,?)',[req.user.id,title.trim(),description.trim(),status,priority,due_date||null]);const [rows]=await db.execute('SELECT id,title,description,status,priority,due_date,created_at,updated_at FROM tasks WHERE id=? AND user_id=?',[result.insertId,req.user.id]);res.status(201).json(rows[0])}catch(err){console.error(err);res.status(500).json({message:'Unable to create task.'})}});

app.get('/api/tasks/:id',requireAuth,async(req,res)=>{try{const [rows]=await db.execute('SELECT id,title,description,status,priority,due_date,created_at,updated_at FROM tasks WHERE id=? AND user_id=?',[req.params.id,req.user.id]);if(!rows.length)return res.status(404).json({message:'Task not found.'});res.json(rows[0])}catch(err){console.error(err);res.status(500).json({message:'Unable to load task.'})}});

app.put('/api/tasks/:id',requireAuth,async(req,res)=>{try{const {title,description='',status,priority,due_date=null}=req.body;if(!title?.trim())return res.status(400).json({message:'Task title is required.'});if(!['pending','in_progress','completed'].includes(status)||!['low','medium','high'].includes(priority))return res.status(400).json({message:'Invalid status or priority.'});const [result]=await db.execute('UPDATE tasks SET title=?,description=?,status=?,priority=?,due_date=? WHERE id=? AND user_id=?',[title.trim(),description.trim(),status,priority,due_date||null,req.params.id,req.user.id]);if(!result.affectedRows)return res.status(404).json({message:'Task not found.'});const [rows]=await db.execute('SELECT id,title,description,status,priority,due_date,created_at,updated_at FROM tasks WHERE id=? AND user_id=?',[req.params.id,req.user.id]);res.json(rows[0])}catch(err){console.error(err);res.status(500).json({message:'Unable to update task.'})}});

app.delete('/api/tasks/:id',requireAuth,async(req,res)=>{try{const [result]=await db.execute('DELETE FROM tasks WHERE id=? AND user_id=?',[req.params.id,req.user.id]);if(!result.affectedRows)return res.status(404).json({message:'Task not found.'});res.json({message:'Task deleted successfully.'})}catch(err){console.error(err);res.status(500).json({message:'Unable to delete task.'})}});

app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'..','public','index.html')));
const port=Number(process.env.PORT||3000);app.listen(port,()=>console.log(`DTEN Task Manager running at http://localhost:${port}`));
